version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  tech_assess_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        options: --reload
    command: gunicorn --reload --config config/gunicorn_config.py wsgi:app
    environment:
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
      MONGODB_URL: mongodb://root:example@mongo:27017/
      MONGODB_DB_NAME: recordings
    depends_on:
      - mongo
    ports: ["8000:8000"]
#
#  tech_assess_frontend:
#    container_name: tech_asses_frontend
#    build:
#      context: frontend
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true