openapi: '3.0.2'

info:
  title: Tech Assessment Backend API
  version: 1.0.0
  contact:
    name: Aidan McKenna
    email: aidantmckenna@gmail.com

servers:
  - url: http://localhost:8000

paths:
  /recordings:
    post:
      summary: Upload a set of recordings
      requestBody:
        description: Asset file and tags
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio_video_file:
                  type: string
                  format: binary
                audio_only_file:
                  type: string
                  format: binary
                video_only_file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Files uploaded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recording"
        '400':
          description: Bad request.
        '5XX':
          description: Unexpected error.

  /recordings/{uuid}:
    parameters:
      - $ref: "#/components/parameters/RecordingUUID"
    get:
      summary: Get recording object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recording"

  /recordings/{uuid}/output:
    parameters:
      - $ref: "#/components/parameters/RecordingUUID"
    get:
      summary: Get recording combined output video
      responses:
        '200':
          description: OK
          content: video/mp4


components:
  schemas:
    Recording:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        audio_video_filepath:
          type: string
        audio_only_filepath:
          type: string
        video_only_filepath:
          type: string

  parameters:
    RecordingUUID:
      in: path
      name: recording_uuid
      required: true
      schema:
        type: string
        format: uuid
